version: '3.4'

services:
  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8080:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
